import { Language } from "./types";

export const translations: Record<Language, any> = {
  en: {
    title: "Petro One Fuel Services",
    subtitle: "Fueling the Future, One Station at a Time",
    addStation: "Register New Station",
    stationName: "Station Name",
    ownerOperator: "Owner / Operator",
    contractType: "Contract Type",
    latitude: "Latitude",
    longitude: "Longitude",
    status: "Current Status",
    construction: "Under Construction",
    active: "Operating",
    progress: "Execution Progress",
    license: "License Number",
    save: "Add Station",
    switchLang: "العربية",
    totalStations: "Total Managed Stations",
    operating: "Operating Stations",
    underConstruction: "Under Construction",
    averageProgress: "Avg. Construction Progress",
    listConstruction: "Construction Roadmap",
    listActive: "Active Portfolio",
    noStations: "No stations recorded yet.",
    mapPlaceholder: "Interactive Network Map",
    mapDesc: "Global visualization of Petro One assets. Blue markers indicate active stations, yellow markers represent projects in progress.",
    stationDetails: "Station Details",
    lastUpdated: "Last Updated",
    dir: "ltr"
  },
  ar: {
    title: "بترو ون للخدمات البترولية",
    subtitle: "تزويد المستقبل، محطة تلو الأخرى",
    addStation: "تسجيل محطة جديدة",
    stationName: "اسم المحطة",
    ownerOperator: "المالك / المشغل",
    contractType: "نوع التعاقد",
    latitude: "خط العرض",
    longitude: "خط الطول",
    status: "الحالة الحالية",
    construction: "تحت الإنشاء",
    active: "قيد التشغيل",
    progress: "نسبة الإنجاز",
    license: "رقم الرخصة",
    save: "إضافة المحطة",
    switchLang: "English",
    totalStations: "إجمالي المحطات المدارة",
    operating: "محطات قيد التشغيل",
    underConstruction: "محطات تحت الإنشاء",
    averageProgress: "متوسط نسبة الإنجاز",
    listConstruction: "خارطة طريق الإنشاء",
    listActive: "المحفظة النشطة",
    noStations: "لا توجد محطات مسجلة حتى الآن.",
    mapPlaceholder: "خريطة الشبكة التفاعلية",
    mapDesc: "تصوير عالمي لأصول بترو ون. تشير العلامات الزرقاء إلى المحطات النشطة، بينما تمثل العلامات الصفراء المشاريع الجاري تنفيذها.",
    stationDetails: "تفاصيل المحطة",
    lastUpdated: "آخر تحديث",
    dir: "rtl"
  },
};
